config/routes.rb
Rails.application.routes.draw do

  resources :notifications, only: [:index, :show] do
    post :mark_all_as_read, on: :collection
  end

  root 'home#show'

  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  get '/auth/failure' => 'sessions#new', error: true
  get '/signout' => 'sessions#destroy', as: :signout
  resource :session, only: [:new, :create, :destroy]

  resource :profile, only: [:edit, :update]
  resource :public_comments, only: [:create], controller: :comments, type: 'PublicComment'
  resource :internal_comments, only: [:create], controller: :comments, type: 'InternalComment'
  resources :speakers, only: [:destroy]
  resources :proposals, only: [:index]
  resources :events, only: [:index]
  scope '/events/:slug' do
    get '/' => 'events#show', as: :event

    post '/proposals' => 'proposals#create', as: :event_proposals
    get 'parse_edit_field' => 'proposals#parse_edit_field',
        as: :parse_edit_field_proposal

    resources :proposals, param: :uuid do
      member { get :confirm }
      member { post :set_confirmed }
      member { post :withdraw }
      member { delete :destroy }
    end
  end

  resources :participant_invitations, only: :show, param: :slug do
    member do
      get ":token/accept", action: :accept, as: :accept
      get ":token/refuse", action: :refuse, as: :refuse
    end
  end

  resources :invitations, only: [:show, :create, :destroy], param: :invitation_slug do
    member do
      post :accept, action: :update
      post :refuse, action: :update, refuse: true
      post :resend, action: :resend
    end
  end

  namespace 'admin' do
    resources :events, except: [:show, :edit, :update] do
      post :archive
      post :unarchive
    end

    resources :people do
      resources :services
    end
  end

  namespace 'organizer' do
    resources :events, only: [:edit, :show, :update] do
      member do
        get :edit_custom_fields
        put :update_custom_fields
      end
      resources :participant_invitations, except: [:new, :edit, :update, :show]



      controller :program do
        get 'program' => 'program#show'
      end

      resources :participants, only: [:create, :destroy, :update] do
        collection { get :emails, defaults: {format: :json} }
      end

      resources :rooms, only: [:create, :update, :destroy]
      resources :tracks, only: [:create, :destroy]
      resources :sessions, except: :show
      resources :proposals, param: :uuid do
        resources :speakers, only: [:new, :create]
        post :finalize
        post :update_state
      end


      controller :speakers do
        get :speaker_emails, action: :emails
      end
      resources :speakers, only: [:index, :show, :edit, :update, :destroy] do
        member do
          get :profile, to: "profiles#edit", as: :edit_profile
          patch :profile, to: "profiles#update", as: :update_profile
        end
      end
    end

  end

  namespace 'reviewer' do
    resources :events, only: [:show] do
      resources :participants, only: [:update]
      resources :proposals, only: [:index, :show, :update], param: :uuid do
        resources :ratings, only: [:create, :update], defaults: {format: :js}
      end
    end
  end

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::ApplicationController
  before_filter :require_event, only: [:destroy]

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
			@event.participants.create(person: current_user, role: 'organizer')
      flash[:info] = 'Your event was saved.'
      redirect_to organizer_event_url(@event)
    else
      flash[:danger] = 'There was a problem saving your event; please review the form for issues and try again.'
      render :new
    end
  end

  def destroy
    @event.destroy
    flash[:info] = "Your event has been deleted."
    redirect_to events_url
  end

  def archive
    @event = Event.find_by(id: params[:event_id])
    if @event
      @event.archive
      flash[:warning] = "#{@event.name} is now archived."
    else
      flash[:danger] = "Event not found. Unable to archive."
    end
    redirect_to admin_events_url
  end

  def unarchive
    @event = Event.find_by(id: params[:event_id])
    if @event
      @event.unarchive
      flash[:warning] = "#{@event.name} is now current."
    else
      flash[:danger] = "Event not found. Unable to unarchive."
    end
    redirect_to admin_events_url
  end

  def index
    @events = Event.order("archived").all
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :require_event, only: [:show]

  def index
    render locals: {
      events: Event.recent.decorate
    }
  end

  def show
  end
end

app/controllers/organizer/application_controller.rb
class Organizer::ApplicationController < ApplicationController
  before_action :require_event
  before_filter :require_organizer

  private

  def require_event
    @event = current_user &&
      current_user.organizer_events.find(params[:event_id] || params[:id])
  end

  # Must be an organizer on @event
  def require_organizer
    unless @event
      session[:target] = request.path
      flash[:danger] = "You must be signed in as an organizer to access this page."
      redirect_to new_session_url
    end
  end

  def organizer_signed_in?
    user_signed_in? && @event && current_user.organizer_for_event?(@event)
  end
end

app/controllers/organizer/events_controller.rb
class Organizer::EventsController < Organizer::ApplicationController

  def edit
    @partial = 'admin/events/form'
    if params[:form]
      @partial = "admin/events/#{params[:form]}"
    end
  end

  def show
    participants = @event.participants.includes(:person).recent
    rating_counts = @event.ratings.group(:person_id).count

    render locals: {
             event: @event.decorate,
             rating_counts: rating_counts,
             participants: participants
           }
  end

  def edit_custom_fields
    @event = Event.find(params[:id])
  end

  def update_custom_fields
    if @event.update_attributes(event_params)
      flash[:info] = 'Your event was saved.'
      redirect_to organizer_event_url(@event)
    else
      flash[:danger] = flash[:danger] = 'There was a problem saving your event; please review the form for issues and try again.'
      render :edit_custom_fields
    end
  end

  def update
    if @event.update_attributes(event_params)
      flash[:info] = 'Your event was saved.'
      redirect_to organizer_event_url(@event)
    else
      flash[:danger] = 'There was a problem saving your event; please review the form for issues and try again.'
      render :edit
    end
  end
end

app/controllers/organizer/participant_invitations_controller.rb
class Organizer::ParticipantInvitationsController < Organizer::ApplicationController
  before_action :set_participant_invitation, only: [ :destroy ]

  decorates_assigned :participant_invitation

  # GET /participant_invitations
  def index
    render locals: {
      participant_invitations: @event.participant_invitations
    }
  end

  # POST /participant_invitations
  def create
    @participant_invitation =
      @event.participant_invitations.build(participant_invitation_params)

    if @participant_invitation.save
      ParticipantInvitationMailer.create(@participant_invitation).deliver_now
      redirect_to organizer_event_participant_invitations_url(@event),
        flash: { info: 'Participant invitation successfully sent.' }
    else
      redirect_to organizer_event_participant_invitations_path(@event),
        flash: { danger: 'There was a problem creating your invitation.' }
    end
  end

  # DELETE /participant_invitations/1
  def destroy
    @participant_invitation.destroy

    redirect_to organizer_event_participant_invitations_url(@event),
      flash: { info: 'Participant invitation was successfully removed.' }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant_invitation
      @participant_invitation =
        @event.participant_invitations.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def participant_invitation_params
      params.require(:participant_invitation).permit(:email, :role)
    end
end

app/controllers/organizer/participants_controller.rb
class Organizer::ParticipantsController < Organizer::ApplicationController
  respond_to :html, :json

  def create
    person = Person.where(email: params[:email]).first
    if person.nil?
      participant_invitation =
        @event.participant_invitations.build(participant_params.merge(email: params[:email]))

      if participant_invitation.save
        ParticipantInvitationMailer.create(participant_invitation).deliver_now
        flash[:info] = 'Participant invitation successfully sent.'
      else
        flash[:danger] = 'There was a problem creating your invitation.'
      end
      redirect_to organizer_event_participant_invitations_url(@event)
    else
      participant = @event.participants.build(participant_params.merge(person: person))

      if participant.save
        flash[:info] = 'Your participant was added.'
      else
        flash[:danger] = "There was a problem saving your participant. Please try again"
      end
      redirect_to organizer_event_url(@event)
    end
  end

  def update
    participant = Participant.find(params[:id])
    participant.update(participant_params)

    flash[:info] = "You have successfully changed your participant."
    redirect_to organizer_event_url(@event)
  end

  def destroy
    @event.participants.find(params[:id]).destroy

    flash[:info] = "Your participant has been deleted."
    redirect_to organizer_event_url(@event)
  end

  def emails
    emails = Person.where("email like ?",
                          "%#{params[:term]}%").order(:email).pluck(:email)
    respond_with emails.to_json, format: :json
  end

  private

  def participant_params
    params.require(:participant).permit(:role, :notifications)
  end
end

app/controllers/organizer/profiles_controller.rb
class Organizer::ProfilesController < Organizer::ApplicationController

  def edit
    @person = Speaker.find(params[:id]).person
  end

  def update
    @person = Speaker.find(params[:id]).person
    if @person.update(person_params)
      redirect_to organizer_event_speakers_url(event)
    else
      if @person.email == ""
        @person.errors[:email].clear
        @person.errors[:email] = " can't be blank"
      end
      flash.now[:danger] = "Unable to save profile. Please correct the following: #{@person.errors.full_messages.join(', ')}."
      render :edit
    end
  end

  private

  def person_params
    params.require(:person).permit(:bio, :gender, :ethnicity, :country, :name, :email)
  end
end

app/controllers/organizer/program_controller.rb
class Organizer::ProgramController < Organizer::ApplicationController
  def show
    accepted_proposals =
      @event.proposals.includes(:session).for_state(Proposal::State::ACCEPTED)

    waitlisted_proposals = @event.proposals.for_state(Proposal::State::WAITLISTED)

    session[:prev_page] = { name: 'Program', path: organizer_event_program_path(@event) }

    respond_to do |format|
      format.html do
        render locals: {
          accepted_proposals:
            ProposalDecorator.decorate_collection(accepted_proposals),
          waitlisted_proposals:
            ProposalDecorator.decorate_collection(waitlisted_proposals),
          accepted_confirmed_count: accepted_proposals.to_a.count(&:confirmed?),
          waitlisted_confirmed_count: waitlisted_proposals.to_a.count(&:confirmed?)
        }
      end

      format.json { render_json(accepted_proposals.confirmed) }
    end
  end
end

app/controllers/organizer/proposals_controller.rb
class Organizer::ProposalsController < Organizer::ApplicationController
  before_filter :require_proposal, except: [:index, :new, :create, :edit_all]

  decorates_assigned :proposal, with: Organizer::ProposalDecorator

  def finalize
    @proposal.finalize
    send_state_mail(@proposal.state)
    redirect_to organizer_event_proposal_url(@proposal.event, @proposal)
  end

  def update_state
    @proposal.update_state(params[:new_state])

    respond_to do |format|
      format.html { redirect_to organizer_event_proposals_path(@proposal.event) }
      format.js
    end
  end

  def index
    proposals = @event.proposals.includes(:event, :review_taggings, :proposal_taggings, :ratings, {speakers: :person}).load

    session[:prev_page] = {name: 'Proposals', path: organizer_event_proposals_path}

    taggings_count = Tagging.count_by_tag(@event)

    proposals = Organizer::ProposalsDecorator.decorate(proposals)
    respond_to do |format|
      format.html { render locals: {event: @event, proposals: proposals, taggings_count: taggings_count} }
      format.csv { render text: proposals.to_csv }
    end
  end

  def show
    set_title(@proposal.title)
    other_proposals = []
    @proposal.speakers.each do |speaker|
      speaker.proposals.each do |p|
        if p.id != @proposal.id && p.event_id == @event.id
          other_proposals << p
        end
      end
    end

    current_user.notifications.mark_as_read_for_proposal(reviewer_event_proposal_url(@event, @proposal))
    render locals: {
             speakers: @proposal.speakers.decorate,
             other_proposals: Organizer::ProposalsDecorator.decorate(other_proposals),
             rating: current_user.rating_for(@proposal)
           }
  end

  def edit
  end


  def update
    if @proposal.update_without_touching_updated_by_speaker_at(proposal_params)
      flash[:info] = 'Proposal Updated'
      redirect_to organizer_event_proposals_url(slug: @event.slug)
    else
      flash[:danger] = 'There was a problem saving your proposal; please review the form for issues and try again.'
      render :edit
    end
  end

  def destroy
    @proposal.destroy
    flash[:info] = "Your proposal has been deleted."
    redirect_to organizer_event_proposals_url(@event)
  end

  def new
    @proposal = @event.proposals.new
    @speaker = @proposal.speakers.build
    @person = @speaker.build_person
  end

  def create
    altered_params = proposal_params.merge!("state" => "accepted", "confirmed_at" => DateTime.now)
    @proposal = @event.proposals.new(altered_params)
    if @proposal.save
      flash[:success] = 'Proposal Added'
      redirect_to organizer_event_program_url(@event)
    else
      flash.now[:danger] = 'There was a problem saving your proposal; please review the form for issues and try again.'
      render :new
    end
  end

  private

  def proposal_params
    # add updating_person to params so Proposal does not update last_change attribute when updating_person is organizer_for_event?
    params.require(:proposal).permit(:title, {review_tags: []}, :abstract, :details, :pitch, :slides_url, :video_url, custom_fields: @event.custom_fields,
                                     comments_attributes: [:body, :proposal_id, :person_id],
                                     speakers_attributes: [:bio, :person_id, :id,
                                                           person_attributes: [:id, :name, :email, :bio]])
  end

  def send_state_mail(state)
    case state
      when Proposal::State::ACCEPTED
        Organizer::ProposalMailer.accept_email(@event, @proposal).deliver_now
      when Proposal::State::REJECTED
        Organizer::ProposalMailer.reject_email(@event, @proposal).deliver_now
      when Proposal::State::WAITLISTED
        Organizer::ProposalMailer.waitlist_email(@event, @proposal).deliver_now
    end
  end
end

app/controllers/organizer/rooms_controller.rb
class Organizer::RoomsController < Organizer::SchedulesController

  before_filter :set_sessions, only: [:update, :destroy]

  def create
    room = @event.rooms.build(room_params)
    unless room.save
      flash.now[:warning] = "There was a problem saving your room"
    end

    respond_to do |format|
      format.js do
        render locals: { room: room }
      end
    end
  end

  def update
    room = Room.find params[:id]
    room.update_attributes(room_params)

    respond_to do |format|
      format.js do
        render locals: { room: room }
      end
    end
  end

  def destroy
    room = @event.rooms.find(params[:id]).destroy

    flash.now[:info] = "This room has been deleted."
    respond_to do |format|
      format.js do
        render locals: { room: room }
      end
    end
  end

  private

  def room_params
    params.require(:room).permit(:name, :room_number, :level, :address, :capacity, :grid_position)
  end

end

app/controllers/organizer/schedules_controller.rb
class Organizer::SchedulesController < Organizer::ApplicationController
  decorates_assigned :sessions

  protected

  def set_sessions
    @sessions =
      @event.sessions.includes(:track, :room, proposal: { speakers: :person })
  end
end

app/controllers/reviewer/events_controller.rb
class Reviewer::EventsController < Reviewer::ApplicationController
  skip_before_filter :require_proposal

  def show
    participant = Participant.find_by(person_id: current_user)
    rating_counts = @event.ratings.group(:person_id).count
    render locals: {
             event: @event.decorate,
             rating_counts: rating_counts,
             participant: participant
           }
  end

end

app/helpers/organizer/participant_invitations_helper.rb
module Organizer::ParticipantInvitationsHelper
  def new_participant_invitation_button
    link_to 'Invite new participant', '#', class: 'btn btn-primary',
      data: { toggle: 'modal', target: "#new-participant-invitation" },
      id: 'invite-new-participant'
  end
end

app/views/organizer/events/_participant_controls.html.haml
= link_to 'Change Role', '#', class: 'btn btn-primary btn-xs', data: { toggle: 'modal', target: "#participant-change-role-#{participant.id}" }
= link_to 'Remove', organizer_event_participant_path(participant.event, participant), method: :delete, data: { confirm: "Are you sure you want to remove this participant?" }, class: 'btn btn-danger btn-xs'
%div{ id: "participant-change-role-#{participant.id}", class: 'modal fade' }
  .modal-dialog
    .modal-content
      = form_for participant, url: organizer_event_participant_path(participant.event, participant), html: { role: 'form' } do |f|
        .modal-header
          %h3 Change participant role
        .modal-body
          = f.label :role
          = f.select :role, ['reviewer', 'organizer'], class: 'form-control'
        .modal-footer
          %button.btn.btn-default{'data-dismiss' => "modal"} Cancel
          %button.pull-right.btn.btn-primary{:type => "submit"} Save

app/views/organizer/events/_participant_notifications.html.haml
= link_to 'Change', '#', class: 'btn btn-primary btn-xs', data: { toggle: 'modal', target: "#participant-change-role-#{participant.id}" }
%div{ id: "participant-change-role-#{participant.id}", class: 'modal fade' }
  .modal-dialog
    .modal-content
      = form_for participant, url: organizer_event_participant_path(participant.event, participant), html: { role: 'form' } do |f|
        .modal-header
          %h3 Change participant role
        .modal-body
          = f.label :notifications
          = f.check_box :notifications, class: "checkbox"
          = f.label "Check to Receive Comment Notification Emails"

app/views/organizer/events/_participants.html.haml
.row
  %header
    .col-md-3
      %h3 Participants
      = link_to 'view speakers', organizer_event_speakers_path(event)
    .col-sm-1.col-sm-offset-6
      = link_to 'Add/Invite New Participant', '#', class: 'btn btn-primary', data: { toggle: 'modal', target: "#new-participant-event-#{event.id}" }
      = link_to 'Manage Participant Invitations',
        organizer_event_participant_invitations_path(event), class: 'btn btn-primary'
.row
  .col-md-11
    %table.participants.table.table-striped
      %thead
        %tr
          %th Name
          %th Email
          %th Rated Proposals
          %th Role
          %th.notifications Comment Notifications
          %th.actions Actions
      %tbody
        - participants.each do |participant|
          %tr
            %td= participant.person.name
            %td= participant.person.email
            %td= rating_counts[participant.person.id] || 0
            %td= participant.role
            %td.notifications
              = participant.comment_notifications
              - if participant.person == current_user
                = render partial: 'organizer/events/participant_notifications', locals: {participant: participant}
            %td.actions
              - unless participant.person == current_user
                = render partial: 'organizer/events/participant_controls', locals: { participant: participant }
%div{ id: "new-participant-event-#{event.id}", class: 'modal fade' }
  .modal-dialog
    .modal-content
      = form_for event.participants.build, url: organizer_event_participants_path(event), html: {role: 'form'} do |f|
        .modal-header
          %h3 Add/Invite a participant to #{event.name}
        .modal-body
          .form-group
            = label_tag :email
            = text_field_tag :email, '', class: 'form-control',
              id: 'autocomplete-email',
              placeholder: "Participant's email",
              data: { path: emails_organizer_event_participants_path(event) }
          .form-group
            = f.label :role
            = f.select :role, ['reviewer', 'organizer'], class: 'form-control'
        .modal-footer
          %button.btn.btn-default{'data-dismiss' => "modal"} Cancel
          %button.pull-right.btn.btn-success{:type => "submit"} Save

app/views/organizer/events/edit.html.haml
%h1
  Edit #{event}
= form_for event, url: organizer_event_path(event), html: {role: 'form'} do |f|
  = render partial: @partial, locals: {f: f}

app/views/organizer/events/edit_custom_fields.html.haml
%h2 Custom Fields
.form-group
  = form_for @event, :url => update_custom_fields_organizer_event_path, :method => :put  do |f|
    = f.text_field :custom_fields_string
    %p.help-block This is a comma separated list of custom fields allowed for use on proposals.
    %button.pull-right.btn.btn-success{:type => "submit"} Save

app/views/organizer/events/show.html.haml
.event
  .row
    %header
      .col-sm-3
        %h2= event
      .col-sm-5.col-sm-offset-4
        #event-actions-top.pull-right
          = link_to "Proposals", organizer_event_proposals_path(event), class: "btn btn-default"
          = link_to "Program", organizer_event_program_path(event), class: "btn btn-default"
          = link_to "Schedule", organizer_event_sessions_path(event), class: "btn btn-default"
          = link_to "Edit Event", edit_organizer_event_path(event), class: "btn btn-primary"
  .row
    .col-sm-4
      %h4 Event Details
      %dl.dl-horizontal
        %dt Url:
        %dd
          %a{ href: event.url }#{event.url}
        %dt Slug:
        %dd #{event.slug}
        %dt Email:
        %dd #{event.contact_email}
        %dt Guidelines:
        %dd
          -if event.guidelines.present?
            = event.guidelines.truncate(150, separator: /\s/)
          = link_to "Public guidelines", event_path(slug: event.slug)
          %p= link_to "Edit Guidelines", edit_organizer_event_path(:form => "guidelines_form"), class: "btn btn-primary"
      %dl.dl-horizontal
        %dt CFP Opens:
        %dd= event.cfp_opens

        %dt CFP Closes:
        %dd= event.cfp_closes

        .subset
          %dt Days Remaining:
          %dd #{event.cfp_days_remaining}

        %dt Event Start:
        %dd #{event.start_date.to_s(:month_day_year) unless event.start_date.blank?}

        %dt Event End:
        %dd #{event.end_date.to_s(:month_day_year) unless event.end_date.blank?}


    .col-sm-4
      %h4 Proposal Stats
      %dl.dl-horizontal
        %dt Total:
        %dd #{event.proposals.count}
        .subset
          %dt Reviewed:
          %dd #{event.proposals.rated.count} (#{event.reviewed_percent})
        %dt Accepted:
        %dd #{event.proposals.accepted.count}
        .subset
          %dt Confirmed:
          %dd #{event.proposals.accepted.confirmed.count} (#{event.confirmed_percent})
        .subset
          %dt Scheduled:
          %dd #{event.proposals.scheduled.count} (#{event.scheduled_percent})
        %dt Waitlisted:
        %dd #{event.proposals.waitlisted.count}
        .subset
          %dt Confirmed:
          %dd #{event.proposals.waitlisted.confirmed.count} (#{event.waitlisted_percent})
      %h4 Proposal Tags
      %dd=event.valid_proposal_tags
      %dl.dl-horizontal

      %h4 Review Tags
      %dd=event.valid_review_tags
      %dl.dl-horizontal
      %p= link_to "Edit Tags", edit_organizer_event_path(:form => "tags_form"), class: "btn btn-primary"

      %h4 Fields
      %dd=event.fields
      %p= link_to "Add Custom Field", edit_custom_fields_organizer_event_path(event), class: "btn btn-primary"


    .col-sm-4
      %h4 Tracks
      -if event.track_count.present?
        - event.track_count.sort_by{|k,v| v}.reverse.each_slice(8).to_a.each do |row|
          %ul#columns.list-inline
            -row.each do |name, count|
              %li
                .label.label-success
                  = name
                  = count
      -else
        %p No Tracks

    .col-sm-4
      %h4 Speaker Notifcations
      = link_to 'Edit Speaker Notifications', edit_organizer_event_path(:form => "speaker_notifications_form"), class: "btn btn-primary"
      %dt Accept:
      %dd=event.speaker_notification_emails['accept'].truncate(75, separator: /\s/)
      %dt Reject:
      %dd=event.speaker_notification_emails['reject'].truncate(75, separator: /\s/)
      %dt Waitlist:
      %dd=event.speaker_notification_emails['waitlist'].truncate(75, separator: /\s/)


  = render partial: 'participants',
    locals: { event: event, participants: participants,
      rating_counts: rating_counts }