config/routes.rb
Rails.application.routes.draw do

  resources :notifications, only: [:index, :show] do
    post :mark_all_as_read, on: :collection
  end

  root 'home#show'

  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  get '/auth/failure' => 'sessions#new', error: true
  get '/signout' => 'sessions#destroy', as: :signout
  resource :session, only: [:new, :create, :destroy]

  resource :profile, only: [:edit, :update]
  resource :public_comments, only: [:create], controller: :comments, type: 'PublicComment'
  resource :internal_comments, only: [:create], controller: :comments, type: 'InternalComment'
  resources :speakers, only: [:destroy]
  resources :proposals, only: [:index]
  resources :events, only: [:index]
  scope '/events/:slug' do
    get '/' => 'events#show', as: :event

    post '/proposals' => 'proposals#create', as: :event_proposals
    get 'parse_edit_field' => 'proposals#parse_edit_field',
        as: :parse_edit_field_proposal

    resources :proposals, param: :uuid do
      member { get :confirm }
      member { post :set_confirmed }
      member { post :withdraw }
      member { delete :destroy }
    end
  end

  resources :participant_invitations, only: :show, param: :slug do
    member do
      get ":token/accept", action: :accept, as: :accept
      get ":token/refuse", action: :refuse, as: :refuse
    end
  end

  resources :invitations, only: [:show, :create, :destroy], param: :invitation_slug do
    member do
      post :accept, action: :update
      post :refuse, action: :update, refuse: true
      post :resend, action: :resend
    end
  end

  namespace 'admin' do
    resources :events, except: [:show, :edit, :update] do
      post :archive
      post :unarchive
    end

    resources :people do
      resources :services
    end
  end

  namespace 'organizer' do
    resources :events, only: [:edit, :show, :update] do
      member do
        get :edit_custom_fields
        put :update_custom_fields
      end
      resources :participant_invitations, except: [:new, :edit, :update, :show]



      controller :program do
        get 'program' => 'program#show'
      end

      resources :participants, only: [:create, :destroy, :update] do
        collection { get :emails, defaults: {format: :json} }
      end

      resources :rooms, only: [:create, :update, :destroy]
      resources :tracks, only: [:create, :destroy]
      resources :sessions, except: :show
      resources :proposals, param: :uuid do
        resources :speakers, only: [:new, :create]
        post :finalize
        post :update_state
      end


      controller :speakers do
        get :speaker_emails, action: :emails
      end
      resources :speakers, only: [:index, :show, :edit, :update, :destroy] do
        member do
          get :profile, to: "profiles#edit", as: :edit_profile
          patch :profile, to: "profiles#update", as: :update_profile
        end
      end
    end

  end

  namespace 'reviewer' do
    resources :events, only: [:show] do
      resources :participants, only: [:update]
      resources :proposals, only: [:index, :show, :update], param: :uuid do
        resources :ratings, only: [:create, :update], defaults: {format: :js}
      end
    end
  end

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"

end

app/models/proposal/state.rb
module Proposal::State

  # TODO: Currently a defect exists in the rake db:migrate task that is
  # causing our files to be loaded more than once. Because our files are being
  # loaded more than once, we are receiving errors stating that these
  # constants have already been defined. Therefore, until this defect is
  # fixed, we need to check to ensure that the constants are not already
  # defined prior to defining them.
  unless const_defined?(:ACCEPTED)
    SOFT_ACCEPTED = 'soft accepted'
    SOFT_WAITLISTED = 'soft waitlisted'
    SOFT_REJECTED = 'soft rejected'
    SOFT_WITHDRAWN = 'soft withdrawn'

    ACCEPTED = 'accepted'
    WAITLISTED = 'waitlisted'
    REJECTED = 'rejected'
    WITHDRAWN = 'withdrawn'
    NOT_ACCEPTED = 'not accepted'
    SUBMITTED = 'submitted'

    FINAL_STATES = [ ACCEPTED, WAITLISTED, REJECTED, WITHDRAWN, NOT_ACCEPTED ]

    SOFT_TO_FINAL = {
      SOFT_ACCEPTED => ACCEPTED,
      SOFT_REJECTED => REJECTED,
      SOFT_WAITLISTED => WAITLISTED,
      SOFT_WITHDRAWN => WITHDRAWN
    }
  end
end

app/controllers/organizer/proposals_controller.rb
class Organizer::ProposalsController < Organizer::ApplicationController
  before_filter :require_proposal, except: [:index, :new, :create, :edit_all]

  decorates_assigned :proposal, with: Organizer::ProposalDecorator

  def finalize
    @proposal.finalize
    send_state_mail(@proposal.state)
    redirect_to organizer_event_proposal_url(@proposal.event, @proposal)
  end

  def update_state
    @proposal.update_state(params[:new_state])

    respond_to do |format|
      format.html { redirect_to organizer_event_proposals_path(@proposal.event) }
      format.js
    end
  end

  def index
    proposals = @event.proposals.includes(:event, :review_taggings, :proposal_taggings, :ratings, {speakers: :person}).load

    session[:prev_page] = {name: 'Proposals', path: organizer_event_proposals_path}

    taggings_count = Tagging.count_by_tag(@event)

    proposals = Organizer::ProposalsDecorator.decorate(proposals)
    respond_to do |format|
      format.html { render locals: {event: @event, proposals: proposals, taggings_count: taggings_count} }
      format.csv { render text: proposals.to_csv }
    end
  end

  def show
    set_title(@proposal.title)
    other_proposals = []
    @proposal.speakers.each do |speaker|
      speaker.proposals.each do |p|
        if p.id != @proposal.id && p.event_id == @event.id
          other_proposals << p
        end
      end
    end

    current_user.notifications.mark_as_read_for_proposal(reviewer_event_proposal_url(@event, @proposal))
    render locals: {
             speakers: @proposal.speakers.decorate,
             other_proposals: Organizer::ProposalsDecorator.decorate(other_proposals),
             rating: current_user.rating_for(@proposal)
           }
  end

  def edit
  end


  def update
    if @proposal.update_without_touching_updated_by_speaker_at(proposal_params)
      flash[:info] = 'Proposal Updated'
      redirect_to organizer_event_proposals_url(slug: @event.slug)
    else
      flash[:danger] = 'There was a problem saving your proposal; please review the form for issues and try again.'
      render :edit
    end
  end

  def destroy
    @proposal.destroy
    flash[:info] = "Your proposal has been deleted."
    redirect_to organizer_event_proposals_url(@event)
  end

  def new
    @proposal = @event.proposals.new
    @speaker = @proposal.speakers.build
    @person = @speaker.build_person
  end

  def create
    altered_params = proposal_params.merge!("state" => "accepted", "confirmed_at" => DateTime.now)
    @proposal = @event.proposals.new(altered_params)
    if @proposal.save
      flash[:success] = 'Proposal Added'
      redirect_to organizer_event_program_url(@event)
    else
      flash.now[:danger] = 'There was a problem saving your proposal; please review the form for issues and try again.'
      render :new
    end
  end

  private

  def proposal_params
    # add updating_person to params so Proposal does not update last_change attribute when updating_person is organizer_for_event?
    params.require(:proposal).permit(:title, {review_tags: []}, :abstract, :details, :pitch, :slides_url, :video_url, custom_fields: @event.custom_fields,
                                     comments_attributes: [:body, :proposal_id, :person_id],
                                     speakers_attributes: [:bio, :person_id, :id,
                                                           person_attributes: [:id, :name, :email, :bio]])
  end

  def send_state_mail(state)
    case state
      when Proposal::State::ACCEPTED
        Organizer::ProposalMailer.accept_email(@event, @proposal).deliver_now
      when Proposal::State::REJECTED
        Organizer::ProposalMailer.reject_email(@event, @proposal).deliver_now
      when Proposal::State::WAITLISTED
        Organizer::ProposalMailer.waitlist_email(@event, @proposal).deliver_now
    end
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_filter :require_event, except: :index
  before_filter :require_user
  before_filter :require_proposal, except: [ :index, :create, :new, :parse_edit_field ]
  before_filter :require_speaker, only: [:show, :edit, :update]
  before_filter :require_waitlisted_or_accepted_state, only: [:confirm]

  decorates_assigned :proposal

  def index
    proposals = current_user.proposals.decorate.to_a.group_by(&:event)

    render locals: {
      proposals: proposals,
      invitations: current_user.invitations.decorate
    }
  end

  def new
    @proposal = Proposal.new(event: @event)
    @proposal.speakers.build(person: current_user)
  end

  def confirm

  end

  def set_confirmed
    @proposal.update(confirmed_at: DateTime.now,
                     confirmation_notes: params[:confirmation_notes])
    redirect_to confirm_proposal_url(slug: @proposal.event.slug, uuid: @proposal),
      flash: { success: 'Thank you for confirming your participation' }
  end

  def withdraw
    @proposal.withdraw unless @proposal.confirmed?
    flash[:info] = "Your withdrawal request has been submitted."
    redirect_to proposal_url(slug: @proposal.event.slug, uuid: @proposal)
  end

  def destroy
    @proposal.destroy
    flash[:info] = "Your proposal has been deleted."
    redirect_to proposals_url
  end

  def create
    @proposal = @event.proposals.new(proposal_params)

    if @proposal.save
      current_user.update_bio
      flash[:info] = setup_flash_message

      if current_user.demographics_complete?
        redirect_to proposal_url(slug: @event.slug, uuid: @proposal)
      else
        flash[:warning] = "Please consider filling out the demographic data in your profile."
        redirect_to edit_profile_url
      end
    else
      flash[:danger] = 'There was a problem saving your proposal; please review the form for issues and try again.'
      render :new
    end
  end

  def show
    render locals: {
      invitations: @proposal.invitations.not_accepted.decorate
    }
  end

  def edit
  end

  def update
    if params[:confirm]
      @proposal.update(confirmed_at: DateTime.now)
      redirect_to proposal_url(slug: @event.slug, uuid: @proposal), flash: { success: 'Thank you for confirming your participation' }
    elsif @proposal.update_and_send_notifications(proposal_params)
      flash[:info] = 'Please consider filling out the demographic data in your profile.' unless current_user.demographics_complete?
      redirect_to proposal_url(slug: @event.slug, uuid: @proposal)
    else
      flash[:danger] = 'There was a problem saving your proposal; please review the form for issues and try again.'
      render :edit
    end
  end

  include ApplicationHelper
  def parse_edit_field
    respond_to do |format|
      format.js do
        render locals: {
          field_id: params[:id],
          text: markdown(params[:text])
        }
      end
    end
  end

  private

  def proposal_params
    params.require(:proposal).permit(:title, {tags: []}, :abstract, :details, :pitch, custom_fields: @event.custom_fields,
                                     comments_attributes: [:body, :proposal_id, :person_id],
                                     speakers_attributes: [:bio, :person_id, :id])
  end

  def require_speaker
    raise ActiveRecord::RecordNotFound unless current_user.proposal_ids.include?(@proposal.id)
  end

  def setup_flash_message
    message = "Thank you for submitting a proposal."

    if @event.closes_at
      message +=
        " Expect a response after the CFP closes on #{@event.closes_at.to_s(:long)}."
    end
  end

  def require_waitlisted_or_accepted_state
    unless @proposal.waitlisted? || @proposal.accepted?
      redirect_to event_url(@event.slug)
    end
  end
end

app/controllers/reviewer/proposals_controller.rb
class Reviewer::ProposalsController < Reviewer::ApplicationController
  skip_before_filter :require_proposal, only: :index
  skip_before_filter :prevent_self, only: :index

  decorates_assigned :proposal, with: Reviewer::ProposalDecorator
  respond_to :html, :js


  def index
    proposal_ids = current_user.proposals.pluck(:id)

    proposals = @event.proposals.not_withdrawn.includes(:proposal_taggings, :review_taggings,
                                                        :ratings, :internal_comments, :public_comments).where.not(id: proposal_ids)

    proposals.to_a.sort_by! { |p| [p.ratings.present? ? 1 : 0, p.created_at] }
    proposals = Reviewer::ProposalDecorator.decorate_collection(proposals)

    render locals: {
             proposals: proposals
           }

  end

  def show
    set_title(@proposal.title)
    rating = current_user.rating_for(@proposal)
    current_user.notifications.mark_as_read_for_proposal(request.url)
    render locals: {
             rating: rating
           }
    rating.touch unless rating.new_record?
  end

  def update
      unless @proposal.update_without_touching_updated_by_speaker_at(proposal_params)
        flash[:danger] = 'There was a problem saving the proposal.'
      else
        flash[:info] = 'Review Tags were saved for this proposal'
      end
    end

    private

    def proposal_params
      params.fetch(:proposal, {}).permit({review_tags: []})
    end
end

app/helpers/proposal_helper.rb
module ProposalHelper
  def rating_tooltip
      <<-HTML
      <p>Ratings Guide</p>
     <p> 1 - Poor talk with many issues. Not a fit for the event.</p>
     <p> 2 - Mediocre talk that might fit event if they work on it.</p>
     <p> 3 - Good talk, could use improvement but appropriate for the event.</p>
     <p> 4 - Great talk, on topic and an overall fit for the event.</p>
     <p> 5 - Ideal talk, excellent proposal that is a perfect fit for the event.</p>
      HTML
  end
end

app/views/proposals/_comments.html.haml
- if comments.empty?
  None

- comments.order(:created_at).each do |comment|
  .comment.markdown{ class: choose_class_for(comment) }
    =markdown(comment.body)

    - if comment.person.present?
      .meta
        %small{ title: comment.created_at.to_s }
          #{proposal.has_speaker?(comment.person) ? 'speaker' : comment.person.name} - #{comment.created_at.to_s(:day_at_time)}

= form_for comments.new do |f|
  = f.hidden_field :proposal_id
  .form-group
    = f.text_area :body, class: 'form-control', placeholder: 'Add your comment', rows: 13
  %button.btn.btn-success.save-comment(type="submit")
    %span.glyphicon.glyphicon-ok
    Comment

app/views/proposals/_confirmation_notes.html.haml
- unless proposal.confirmation_notes?
  None

- else
  = proposal.confirmation_notes

app/views/proposals/_contents.html.haml
%h3 Title
.markdown{ data: { 'field-id' => 'proposal_title' } }
  = proposal.title

%h3 Abstract
.markdown{ data: { 'field-id' => 'proposal_abstract' } }
  = proposal.abstract

%h3 Details
.markdown{ data: { 'field-id' => 'proposal_details' } }
  = proposal.details

%h3 Pitch
.markdown{ data: { 'field-id' => 'proposal_pitch' } }
  =proposal.pitch

  - if proposal.custom_fields.any?
    - proposal.proposal_data[:custom_fields].select do |key,value|
      %h3= key.capitalize
      %div
      = value.capitalize
      %div

app/views/proposals/_form.html.haml
.row
  %fieldset.col-md-6
    %p
      Read the #{link_to 'guidelines', event_path(event.slug)} to maximize
      your chance of approval. Refrain from including any information that
      would allow a reviewer to identify you. All fields support
      %a{href: 'https://help.github.com/articles/github-flavored-markdown'}
        GitHub Flavored Markdown.
    = proposal.title_input(f)
    = proposal.abstract_input(f)

    %h3 For Review Committee
    %p.help-block
      This content will
      %strong only
      be visible to the review committee.

    = f.input :details, input_html: { class: 'watched', rows: 10 },
      placeholder: 'Explain the theme and flow of your talk. What are the intended audience takeaways?',
      hint: 'Include any pertinent details such as outlines, outcomes or intended audience.'

    = f.input :pitch, input_html: { class: 'watched', rows: 5 },
      placeholder: 'Why is this talk pertinent? What is your involvement in the topic?',
      hint: 'Explain why this talk should be considered and what makes you qualified to speak on the topic.'


  %fieldset.col-md-6
    - if event.proposal_tags.any?
      %h3 Tags
      = f.select :tags,
        options_for_select(event.proposal_tags, proposal.object.tags),
        {}, {class: 'multiselect proposal-tags', multiple: true }

    - if event.custom_fields.any?
      %h3 Custom Fields
    - event.custom_fields.each do |custom_field|
      .form-group
      = f.label custom_field
      = text_field_tag "proposal[custom_fields][#{custom_field}]", proposal.custom_fields[custom_field], class: "form-control"


    = render partial: 'speakers/fields', locals: { f: f }

    = render partial: 'preview', locals: { proposal: proposal }

    .form-submit.clearfix
      %button.pull-right.btn.btn-primary.btn-lg{:type => "submit"} Submit Proposal

app/views/proposals/_preview.html.haml
#proposal-preview.panel.panel-default{ data: { 'remote-url' => parse_edit_field_proposal_path(event.slug) } }
  .panel-heading
    %h2.panel-title Preview
  .panel-body
    = render partial: 'proposals/contents', locals: { proposal: proposal }

app/views/proposals/confirm.html.haml
#proposal
  .row
    .col-md-12
      %p
      - if current_user.organizer_for_event?(@event)
        = link_to "Back to Proposal", organizer_event_proposal_path(@proposal.event_id, @proposal.uuid), class: "btn btn-primary"
      - else
        = link_to "Back to Proposal", proposal_path(slug: proposal.event.slug, uuid: proposal), class: "btn btn-primary"
      %h1
        Confirm
        = proposal.title
  .row
    .col-md-8
      - if current_user.organizer_for_event?(@event)
        %p.help-block Please ensure the information below is correct.
      - else
        %p.help-block Congratulations! Your talk has been #{proposal.state}. Please ensure the information below is correct.

      %h3 Abstract
      = proposal.abstract
      %h3 Speakers
      = render partial: 'speakers/speaker',
        collection: proposal.speakers, locals: { withdraw: false }
    .col-md-4
      - if proposal.confirmed?
        %p This proposal was confirmed on #{proposal.confirmed_at}.
      - elsif proposal.withdrawn?
        %p This proposal has been withdrawn
      - else
        = form_tag(set_confirmed_proposal_path(slug: proposal.event.slug, uuid: proposal)) do
          %fieldset
            .form-group
              = label_tag 'Notes'
              = text_area_tag :confirmation_notes, nil, class: 'form-control', rows: 5,
                placeholder: 'Please note any scheduling conflicts, or any additional information an organizer may need to schedule your talk.'
            .form-submit.clearfix
            - if @proposal.speakers == current_user
              = submit_tag 'Confirm my participation', class: 'btn btn-success'
              = proposal.withdraw_button
            - else
              = submit_tag 'Confirm', class: 'btn btn-success'
              = proposal.withdraw_button

        - if proposal.event.url
          %p.help-block
            More event details available here:
            =link_to( proposal.event.url)

app/views/proposals/edit.html.haml
%h1 Edit #{proposal.title} for #{event}

= simple_form_for proposal, url: proposal_path(event.slug, proposal) do |f|
  = render partial: 'form', locals: {f: f}

app/views/proposals/index.html.haml
%h1 Your Dashboard
.row
  .col-md-8.proposals
    %h2 Proposals
    - if proposals.empty?
      %h3 You don't have any proposals.
    - proposals.each do |event, talks|
      %h3.margin-bottom
        = link_to event.name, event_path(event.slug), class: 'event-title'
        %small= event.status
        - if event.open?
          = link_to 'Submit a proposal', new_proposal_path(slug: event.slug), class: 'btn btn-primary'
      %ul
        - talks.each do |proposal|
          %li.proposal
            %h4= link_to proposal.title, proposal_path(slug: proposal.event.slug, uuid: proposal)
            = proposal.public_state(small: true)
            %p= truncate(proposal.abstract, length: 80)
  .col-md-4.invitations
    %h2 Invitations
    %ul.unstyled
      - invitations.each do |invitation|
        %li
          = invitation.state_label
          = invitation.proposal.title
          - if invitation.pending?
            (
            = invitation.refuse_button(small: true)
            |
            = invitation.accept_button(small: true)
            )

app/views/proposals/new.html.haml
%h1 New Proposal for #{event}
= simple_form_for proposal, url: event_proposals_path(event_id: event) do |f|
  = render partial: 'form', locals: {f: f}

app/views/proposals/parse_edit_field.js.erb
$('[data-field-id=<%= field_id %>]')[0].innerHTML = '<%=j text %>';

app/views/proposals/show.html.haml
#proposal
  .row
    .col-md-8
      %h3
        = link_to proposal.event.name, event_path(slug: proposal.event.slug)
        = ", "
        = proposal.event.start_date.to_s(:month_day_year)
      %h1
        = proposal.title
    .col-md-4
      - if proposal.has_speaker?(current_user)
        .toolbox.pull-right
          .clearfix
            - unless proposal.withdrawn? || proposal.accepted? || proposal.confirmed?
              = link_to edit_proposal_path(slug: event.slug, uuid: proposal), class: 'btn btn-primary' do
                %span.glyphicon.glyphicon-edit
                Edit
              -if proposal.has_reviewer_activity?
                = proposal.withdraw_button
              -else
                = link_to proposal_path, method: :delete, data: {confirm: 'This will delete your talk. Are you sure you want to do this? It can not be undone.'}, class: 'btn btn-warning', id: 'delete' do
                  %span.glyphicon.glyphicon-exclamation-sign
                  Delete Proposal
          %h5.margin-top
            CFP closes
            = event.closes_at(:month_day_year)
  .row
    .col-md-12.tags= proposal.tags

  .row
    .col-md-4
      = render partial: 'proposals/contents', locals: { proposal: proposal }

    .col-md-4
      %h3 Speakers
      = render proposal.speakers

      - if (proposal.has_speaker?(current_user))
        %h3 Invited Speakers
        - invitations.each do |invitation|
          .clearfix
            %ul.invitation
              %li
                = invitation.state_label
                = invitation.email
                .pull-right
                  = link_to 'Resend',
                    resend_invitation_path(invitation_slug: invitation.slug),
                    method: :post,
                    class: 'btn btn-xs btn-primary',
                    disabled: !invitation.pending?
                  = link_to 'Remove',
                    invitation_path(invitation_slug: invitation.slug),
                    method: :delete,
                    class: 'btn btn-xs btn-danger',
                    disabled: !invitation.pending?,
                    data: {confirm: 'Are you sure you want to remove this invitation?'}

        = form_tag invitations_path(proposal_uuid: proposal.uuid), class: 'form-inline speaker' do
          %h3 Invite a Speaker
          = email_field_tag :email, '', placeholder: "Enter an email address.", class: 'form-control'
          %button.btn.btn-success(type="submit")
            %span.glyphicon.glyphicon-envelope
            Invite
    .col-md-4
      %h3 Reviewer Activity
      %p
        = pluralize(proposal.ratings.count, 'review')
        = proposal.public_state

      %h3 Comments
      = render partial: 'proposals/comments',
        locals: { proposal: proposal, comments: proposal.public_comments }